
FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache git curl \
    && go install github.com/air-verse/air@v1.52.3


COPY go.mod go.sum ./
RUN go mod download


COPY . .

EXPOSE 8080


CMD ["air", "-c", ".air.toml"]
